In [1]:
import pandas as pd

In [2]:
import numpy as np

In [5]:
df = pd.read_csv('practice.csv')

In [6]:
df

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Mouse,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410.53
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Headphones,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255.33
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Webcam,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204.24
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Tablet,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738.02
4,ORD10005,CUST1005,2024-01-04,25.0,Male,Karachi,Finance,Phone,Office,1,162362.40,27.21,EasyPaisa,Pending,1.7,4.0,15,162362.40,44178.81,118183.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD10996,CUST1296,2026-07-27,23.0,Female,Rawalpindi,Finance,Webcam,Electronics,6,74056.90,17.14,Cash,Completed,1.4,7.0,6,444341.40,76160.12,368181.28
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Phone,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068.37
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Headphones,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757.28
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Mouse,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464.25
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Phone,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309.06

In [13]:
# grouping by a single column and applying an aggregation function
groupdata_mean= df.groupby('Department')['Net_Amount'].mean()
print(groupdata_mean)

Department
Finance       425169.779661
HR            469482.188571
IT            416100.833333
Marketing     414331.807229
Operations    458891.302469
Sales         399772.477273
Name: Net_Amount, dtype: float64

In [11]:
df['Net_Amount'] = df['Net_Amount'].astype('int64')

In [12]:
df

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Mouse,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Headphones,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Webcam,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Tablet,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738
4,ORD10005,CUST1005,2024-01-04,25.0,Male,Karachi,Finance,Phone,Office,1,162362.40,27.21,EasyPaisa,Pending,1.7,4.0,15,162362.40,44178.81,118183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD10996,CUST1296,2026-07-27,23.0,Female,Rawalpindi,Finance,Webcam,Electronics,6,74056.90,17.14,Cash,Completed,1.4,7.0,6,444341.40,76160.12,368181
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Phone,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Headphones,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Mouse,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Phone,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309

In [15]:
groupdata_sum = df.groupby(['Department','City'])['Unit_Price'].sum()
print(groupdata_sum)

Department  City
Finance     Burewala      1890072.47
            Faisalabad    1139526.25
            Gujranwala    1219014.47
            Islamabad     1653022.29
            Karachi       3713964.08
            Lahore        2765142.47
            Multan        2475458.44
            Peshawar      1922635.48
            Rawalpindi    2741233.40
            Sialkot       1708591.46
HR          Burewala      1787873.05
            Faisalabad    2100457.90
            Gujranwala    2583051.95
            Islamabad     2455482.27
            Karachi       2039937.73
            Lahore        3181048.25
            Multan        1745104.80
            Peshawar      2504571.26
            Rawalpindi    2352547.50
            Sialkot       1588269.57
IT          Burewala      1467752.10
            Faisalabad    1373894.14
            Gujranwala    1851271.26
            Islamabad     1777046.28
            Karachi       1942526.73
            Lahore        2403052.45
            Multan        1305531.08
            Peshawar      1660041.22
            Rawalpindi    2063492.18
            Sialkot       2136709.19
Marketing   Burewala      1626091.52
            Faisalabad    2761329.45
            Gujranwala    1650550.01
            Islamabad     1684234.65
            Karachi       1615524.47
            Lahore        1938521.75
            Multan        1761682.53
            Peshawar      3357422.05
            Rawalpindi    1612057.40
            Sialkot       1719888.89
Operations  Burewala      2196608.20
            Faisalabad    1778827.53
            Gujranwala    2186770.57
            Islamabad     1750585.80
            Karachi       2921404.14
            Lahore        1317123.43
            Multan        2357973.44
            Peshawar      1997601.00
            Rawalpindi    2045706.39
            Sialkot       2757200.94
Sales       Burewala      1999428.12
            Faisalabad    3243534.07
            Gujranwala    2005388.57
            Islamabad     2649659.74
            Karachi       1906889.86
            Lahore        1438642.40
            Multan        2755933.08
            Peshawar      1332435.14
            Rawalpindi    1645413.67
            Sialkot       1784644.09
Name: Unit_Price, dtype: float64

In [18]:
groupdata_sum = df.groupby(['City','Department','Product'])['Unit_Price'].sum()
with open('groupdata_sum.csv', 'w') as f:
    groupdata_sum.to_csv(f)

In [20]:
group_agg = df.groupby(['Department','City'])['Unit_Price'].agg([np.sum, np.mean, np.std])
print(group_agg)

                              sum           mean           std
Department City
Finance    Burewala    1890072.47  111180.733529  51621.738193
           Faisalabad  1139526.25   81394.732143  59856.092384
           Gujranwala  1219014.47  121901.447000  77359.740326
           Islamabad   1653022.29  118073.020714  71493.075404
           Karachi     3713964.08  154748.503333  65534.371587
           Lahore      2765142.47  138257.123500  66516.588413
           Multan      2475458.44  117878.973333  68562.181836
           Peshawar    1922635.48  120164.717500  79439.049169
           Rawalpindi  2741233.40  105432.053846  70122.818981
           Sialkot     1708591.46  113906.097333  57488.968904
HR         Burewala    1787873.05  127705.217857  74001.675604
           Faisalabad  2100457.90  110550.415789  70423.238798
           Gujranwala  2583051.95  129152.597500  67636.303442
           Islamabad   2455482.27  144440.133529  74986.317211
           Karachi     2039937.73  119996.337059  69938.446476
           Lahore      3181048.25  151478.488095  80751.158913
           Multan      1745104.80  134238.830769  72080.029839
           Peshawar    2504571.26  125228.563000  79922.700715
           Rawalpindi  2352547.50  123818.289474  71979.711540
           Sialkot     1588269.57  105884.638000  72665.272953
IT         Burewala    1467752.10   97850.140000  73922.668363
           Faisalabad  1373894.14  124899.467273  55410.123479
           Gujranwala  1851271.26  115704.453750  69533.133691
           Islamabad   1777046.28  118469.752000  84686.727400
           Karachi     1942526.73  129501.782000  62431.086428
           Lahore      2403052.45  141356.026471  70332.713685
           Multan      1305531.08   93252.220000  61772.260199
           Peshawar    1660041.22  138336.768333  87087.356462
           Rawalpindi  2063492.18  147392.298571  86001.354110
           Sialkot     2136709.19  142447.279333  64555.533463
Marketing  Burewala    1626091.52  108406.101333  68698.759216
           Faisalabad  2761329.45  125514.975000  85530.873279
           Gujranwala  1650550.01  110036.667333  72770.910120
           Islamabad   1684234.65  140352.887500  60511.705479
           Karachi     1615524.47  107701.631333  71708.781943
           Lahore      1938521.75  107695.652778  56350.271956
           Multan      1761682.53  110105.158125  70610.792255
           Peshawar    3357422.05  139892.585417  71944.291363
           Rawalpindi  1612057.40  107470.493333  67791.849699
           Sialkot     1719888.89  122849.206429  71259.511230
Operations Burewala    2196608.20  137288.012500  71987.933607
           Faisalabad  1778827.53  127059.109286  71110.429785
           Gujranwala  2186770.57  121487.253889  58895.924639
           Islamabad   1750585.80  109411.612500  63671.676556
           Karachi     2921404.14  121725.172500  69298.521930
           Lahore      1317123.43  164640.428750  45146.710773
           Multan      2357973.44  130998.524444  70277.594496
           Peshawar    1997601.00  153661.615385  56871.900897
           Rawalpindi  2045706.39  120335.670000  72967.440930
           Sialkot     2757200.94  153177.830000  57744.793735
Sales      Burewala    1999428.12   99971.406000  67255.230505
           Faisalabad  3243534.07  120130.891481  71902.090524
           Gujranwala  2005388.57  143242.040714  66596.170654
           Islamabad   2649659.74  126174.273333  78605.313651
           Karachi     1906889.86  136206.418571  73847.344793
           Lahore      1438642.40  119886.866667  70539.200210
           Multan      2755933.08  131234.908571  80324.834520
           Peshawar    1332435.14  121130.467273  77856.558763
           Rawalpindi  1645413.67   86600.719474  48224.527446
           Sialkot     1784644.09  104979.064118  65951.122767

In [24]:
with open('group_agg.csv', 'w') as f:
    f.write(group_agg.to_csv())

In [28]:
# marging and joining dataframes

df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'],
                    'value': [1, 2, 3, 4]})

df2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'],
                    'value': [5, 6, 7, 8]})

In [26]:
df1

  key  value
0   A      1
1   B      2
2   C      3
3   D      4

In [29]:
df2

  key  value
0   B      5
1   D      6
2   E      7
3   F      8

In [30]:
pd.merge(df1, df2, on='key', how='inner')  # inner join

  key  value_x  value_y
0   B        2        5
1   D        4        6

In [31]:
pd.merge(df1, df2, on='key', how='outer')  # outer join

  key  value_x  value_y
0   A      1.0      NaN
1   B      2.0      5.0
2   C      3.0      NaN
3   D      4.0      6.0
4   E      NaN      7.0
5   F      NaN      8.0

In [33]:
df3 =pd.merge(df1,df2, on='key', how='left')  # left join

In [51]:
df3

  key  value_df1  value_df2  salary
0   A          1        0.0    1000
1   B          2        5.0    2000
2   C          3        0.0    3000
3   D          4        6.0    4000

In [35]:
df3['salary'] = [1000, 2000, 3000, 4000]

In [37]:
df3.rename(columns={'value_x': 'value_df1', 'value_y': 'value_df2'}, inplace=True)

In [41]:
df3.isnull().sum()

key          0
value_df1    0
value_df2    2
salary       0
dtype: int64

In [48]:
df3['value_df2'] = df3['value_df2'].fillna(df3['value_df2'].sum())

In [56]:
df3

  key  value_df1  value_df2
0   A          1        0.0
1   B          2        5.0
3   D          4        6.0

In [53]:
df3.drop(['salary'], axis=1, inplace=True)

In [55]:
df3.drop([2], axis=0, inplace=True)