In [ ]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Practice.csv')

In [4]:
df.head(4)

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Mouse,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410.53
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Headphones,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255.33
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Webcam,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204.24
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Tablet,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738.02

In [5]:
df.tail(4)

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Phone,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068.37
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Headphones,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757.28
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Mouse,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464.25
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Phone,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309.06

In [7]:
df.dtypes

Order_ID                   str
Customer_ID                str
Date                       str
Customer_Age           float64
Gender                     str
City                       str
Department                 str
Product                    str
Category                   str
Quantity                 int64
Unit_Price             float64
Discount_Percent       float64
Payment_Method             str
Order_Status               str
Rating                 float64
Delivery_Days          float64
Employee_Experience      int64
Gross_Amount           float64
Discount_Amount        float64
Net_Amount             float64
dtype: object

In [8]:
# Handling Missing Values

df.isnull()

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [9]:
df.isnull().sum()

Order_ID                0
Customer_ID             0
Date                    0
Customer_Age           20
Gender                  0
City                    0
Department              0
Product                 0
Category                0
Quantity                0
Unit_Price              0
Discount_Percent       20
Payment_Method          0
Order_Status            0
Rating                 20
Delivery_Days          20
Employee_Experience     0
Gross_Amount            0
Discount_Amount         0
Net_Amount              0
dtype: int64

In [10]:
df.isnull().any()

Order_ID               False
Customer_ID            False
Date                   False
Customer_Age            True
Gender                 False
City                   False
Department             False
Product                False
Category               False
Quantity               False
Unit_Price             False
Discount_Percent        True
Payment_Method         False
Order_Status           False
Rating                  True
Delivery_Days           True
Employee_Experience    False
Gross_Amount           False
Discount_Amount        False
Net_Amount             False
dtype: bool

In [11]:
df['Order_Status'].fillna('Unknown', inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_32992\2026558767.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Order_Status'].fillna('Unknown', inplace=True)

0      Completed
1      Completed
2       Returned
3      Completed
4        Pending
         ...
995    Completed
996    Completed
997     Returned
998     Returned
999      Pending
Name: Order_Status, Length: 1000, dtype: str

In [12]:
df['Order_Status']

0      Completed
1      Completed
2       Returned
3      Completed
4        Pending
         ...
995    Completed
996    Completed
997     Returned
998     Returned
999      Pending
Name: Order_Status, Length: 1000, dtype: str

In [14]:
# rename a column

df.rename(columns={'Order_Status': 'Order_Status_Updated'}, inplace=True)

In [15]:
df

,Order_ID,Customer_ID,Date,Customer_Age,Gender,City,Department,Product,Category,Quantity,Unit_Price,Discount_Percent,Payment_Method,Order_Status_Updated,Rating,Delivery_Days,Employee_Experience,Gross_Amount,Discount_Amount,Net_Amount
0,ORD10001,CUST1001,2024-01-01,56.0,Male,Lahore,IT,Mouse,Office,6,105836.96,7.97,Cash,Completed,4.1,7.0,1,635021.76,50611.23,584410.53
1,ORD10002,CUST1002,2024-01-01,46.0,Female,Multan,HR,Headphones,Office,7,196373.45,26.87,Cash,Completed,1.4,1.0,9,1374614.15,369358.82,1005255.33
2,ORD10003,CUST1003,2024-01-02,32.0,Male,Burewala,Sales,Webcam,Electronics,4,49330.30,3.10,Cash,Returned,3.1,14.0,12,197321.20,6116.96,191204.24
3,ORD10004,CUST1004,2024-01-03,60.0,Female,Gujranwala,Sales,Tablet,Electronics,1,205153.20,19.70,JazzCash,Completed,1.9,7.0,13,205153.20,40415.18,164738.02
4,ORD10005,CUST1005,2024-01-04,25.0,Male,Karachi,Finance,Phone,Office,1,162362.40,27.21,EasyPaisa,Pending,1.7,4.0,15,162362.40,44178.81,118183.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD10996,CUST1296,2026-07-27,23.0,Female,Rawalpindi,Finance,Webcam,Electronics,6,74056.90,17.14,Cash,Completed,1.4,7.0,6,444341.40,76160.12,368181.28
996,ORD10997,CUST1297,2026-07-28,43.0,Female,Multan,Marketing,Phone,Office,1,88959.78,22.36,JazzCash,Completed,2.2,5.0,10,88959.78,19891.41,69068.37
997,ORD10998,CUST1298,2026-07-29,21.0,Male,Burewala,IT,Headphones,Accessories,6,141366.22,11.37,Bank Transfer,Returned,3.5,4.0,10,848197.32,96440.04,751757.28
998,ORD10999,CUST1299,2026-07-30,36.0,Female,Rawalpindi,Sales,Mouse,Electronics,5,63454.52,9.08,EasyPaisa,Returned,4.2,8.0,6,317272.60,28808.35,288464.25
999,ORD11000,CUST1300,2026-07-31,37.0,Female,Peshawar,Marketing,Phone,Office,4,228864.84,13.78,EasyPaisa,Pending,4.6,4.0,3,915459.36,126150.30,789309.06

In [16]:
# change the data type of a column

df['Order_Status_Updated'] = df['Order_Status_Updated'].astype('category')

In [18]:
df['Customer_Age'] = df['Customer_Age'].fillna(df['Customer_Age'].mean()).astype('int')